### ISSUE TITLE
Web Audio Error

### ISSUE THREAD

**Issue by ghost** [endrift/gbajs#35]
Affecting chrome 43 when loading in a game.

![error](http://i.imgur.com/77F4a03.png)

**Comment by taisel** [comment]
I guess it throws now instead of doing nothing if there wasn't anything to disconnect.

**Comment by Catarax** [comment]
Commenting the line fix the issue for now

**Comment by endrift** [comment]
I love web tech! It's so bad! Cheap fix pushed, I don't care to figure out why the exception is happening in the first place.

**Comment by Catarax** [comment]
It's still broken, you have to add the try{} on the line 37 for fixing Chrome also.

**Comment by taisel** [comment]
Does it need a try catch anyhow? Thought testing for truthiness was enough on the node to disconnect. Anyhow that's a very minor nitpick. Thanks for updating it
